[package]
name = "golinks-rs"
version = "0.1.0"
authors = ["dinoocch <dino.occhialini@gmail.com>"]

[dependencies]
hyper = "0.11.2"
futures = "0.1.14"
lmdb = "0.7.1"
lazy_static = "0.2"
log = "0.3.8"
pretty_env_logger = "0.1.1"
